---
- name: Reload systemd daemon
  service:
    daemon_reload: true

- name: Restart ollama-openwebui
  become_user: ai-runner
  service:
    name: "ollama-openwebui.service"
    state: restarted
    enabled: true
    scope: user
