---
- name: Install fish
  package:
    name: fish
    state: present

- name: Install util-linux-user to change shell
  package:
    name: util-linux-user
    state: present

- name: Get fish shell path
  command:
    cmd: which fish
  register: fish_path_command
  failed_when: fish_path_command.rc != 0

- name: Change sh to fish
  user:
    name: "{{ ansible_user }}"
    shell: "{{ fish_path_command.stdout }}"
  when: ansible_user != "root"
