---
- name: Create directory tree for user
  include_tasks: directory_structure.yml

- name: Set up python for user
  import_tasks: python.yml

- name: Set up vim and install plugins
  import_tasks: vim.yml

- name: Clone and install vercajk git repo
  import_tasks: vercajk.yml
