---
- name: Create directory tree for user
  include_tasks: directory_structure.yml

- name: Set up python for user
  import_tasks: python.yml

- name: Clone and install vercajk git repo
  import_tasks: vercajk.yml

- name: Setup tmux
  import_tasks: tmux.yml

- name: Setup fish shell
  become: true
  become_user: root
  import_tasks: fish.yml
  tags:
    - fish
