---
- name: Ensure if tmux directory exists
  file:
    path: "{{ home_dir }}/.local/share/tmux"
    state: directory
    mode: 0755

- name: Ensure ~/.local/share/tmux/plugins directory exists
  file:
    path: "{{ home_dir }}/.local/share/tmux/plugins"
    state: directory
    mode: "0755"

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ home_dir }}/.local/share/tmux/plugins/tpm"
    update: true
