---
- name: Check if path to my git projects exists
  stat:
    path: "{{ home_dir }}/Documents/git/github/nikromen"
  register: nikromen_git_path

- name: Ensure path to my git projects
  file:
    path: "{{ home_dir }}/Documents/git/github/nikromen"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  when: not nikromen_git_path.stat.exists

- name: Check if vercajk repo exists
  stat:
    path: "{{ home_dir }}/Documents/git/github/nikromen/vercajk"
  register: vercajk_repo

- name: Clone vercajk repo if not exists or update
  ignore_errors: true
  # noqa: latest[git]
  git:
    repo: git@github.com:nikromen/vercajk.git
    dest: "{{ home_dir }}/Documents/git/github/nikromen/vercajk"
  register: git_clone_vercajk
  when: not vercajk_repo.stat.exists

- name: Clone vercajk repo but without ssh if prev task failed
  # noqa: latest[git]
  git:
    repo: https://github.com/nikromen/vercajk.git
    dest: "{{ home_dir }}/Documents/git/github/nikromen/vercajk"
  when: not vercajk_repo.stat.exists and git_clone_vercajk.failed

- name: Install vercajk repo if it was just cloned
  command:
    cmd: make install
    chdir: "{{ home_dir }}/Documents/git/github/nikromen/vercajk"
  changed_when: true
  when: not vercajk_repo.stat.exists
