packages:
  vercajk-cli:
    paths:
      - ./cli
    specfile_path: vercajk-cli.spec
    files_to_sync:
      - vercajk-cli.spec

jobs:
  - job: copr_build
    packages:
      - vercajk-cli
    trigger: pull_request
    targets:
      - fedora-all-x86_64

  - job: copr_build
    packages:
      - vercajk-cli
    trigger: commit
    branch: main
    targets:
      - fedora-all-x86_64
    owner: nikromen
    project: vercajk
