repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [-x]

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.2
    hooks:
      - id: stylua
        args: [--check]

  - repo: local
    hooks:
      - id: hyprland-verify-config
        name: Verify Hyprland config
        entry: hyprland --verify-config
        language: system
        files: \.config/hypr/
        pass_filenames: false
