---
- name: Remove current profile from konsave
  command:
    cmd: konsave --remove {{ profile_name }}
  # if ran, this changes every time
  changed_when: true

- name: Get vercajk path
  command:
    cmd: vercajk path
  register: vercajk_path
  changed_when: false

- name: Import new konsave profile to konsave
  command:
    cmd: konsave --import-profile {{ vercajk_path.stdout }}/ansible/roles/user/konsave/files/{{ profile_name }}.knsv
  # if ran, this changes every time
  changed_when: true

- name: Apply imported profile
  command:
    cmd: konsave --apply {{ profile_name }}
  # if ran, this changes every time
  changed_when: true
