---
- name: Ensure konsave package
  pip:
    name: konsave
    state: present
    extra_args: --user

# TODO: is not idempotent
- name: Import applying konsave changed profile
  import_tasks: apply_profile.yml
