---
- name: Ensure flatpak is installed
  become: true
  become_user: root
  package:
    name: flatpak
    state: present

- name: Enable flathub for user repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install basic flatpak apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_core }}"

- name: Install dev tools
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_dev }}"

- name: Install multimedia tools
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_multimedia }}"

- name: Install multimedia extras
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_multimedia_extras }}"
  tags:
    - multimedia_extras

- name: Install games
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_games }}"
  tags:
    - games

- name: Install IDEs
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ ide }}"
  tags:
    - ide

- name: Install browsers
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_browsers }}"
  tags:
    - flatpak_browsers

- name: Install hyprland gui apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ hyprland_gui_apps }}"

- name: Install productivity apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_productivity }}"
