---
- name: Ensure flatpak is installed
  become: true
  become_user: root
  package:
    name: flatpak
    state: present

- name: Enable flathub for user repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install basic flatpak apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ core }}"

- name: Install communication apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ communication }}"

- name: Install dev tools
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ dev_tools }}"
  tags:
    - dev_tools

- name: Install multimedia tools
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ multimedia }}"

- name: Install multimedia extras
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ multimedia_extra }}"
  tags:
    - multimedia_extra

- name: Install games
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ games }}"
  tags:
    - games

- name: Install browsers
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ browsers }}"
  tags:
    - browsers

- name: Install hyprland gui apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ hyprland_gui_apps }}"

- name: Install productivity apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ productivity }}"
