# assuming there is grub2 on rpm-based systems already
---
- name: Install os-prober to show output console terminal
  package:
    name: os-prober
    state: present

- name: Check grub terminal output console timeout and set it to 10
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT=(?!10$)"
    line: "GRUB_TIMEOUT=10"
  register: grub_timeout

- name: Ensure grub to detect other operating systems
  lineinfile:
    path: /etc/default/grub
    regexp: "GRUB_DISABLE_OS_PROBER=(?!false$)"
    line: "GRUB_DISABLE_OS_PROBER=false"
  register: grub_os_prober

- name: Ensure disabling graphical terminal for grub
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_TERMINAL_OUTPUT=(?!"console")'
    line: 'GRUB_TERMINAL_OUTPUT="console"'
  register: grub_terminal_output

- name: Generate grub configuration file
  command:
    cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: grub_timeout.changed or grub_os_prober.changed or grub_terminal_output.changed
