apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ollama-data

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dynamic-hostpath
  resources:
    requests:
      # this is the minimum size, it is dynamically expanded
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: open-webui-data

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dynamic-hostpath
  resources:
    requests:
      # this is the minimum size, it is dynamically expanded
      storage: 1Gi

---

apiVersion: v1
kind: Pod

metadata:
  name: ollama-pod

spec:
  containers:
    - name: ollama
      image: docker.io/ollama/ollama:rocm
      securityContext:
        seLinuxOptions:
          type: container_runtime_t
      volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        - name: kfd
          mountPath: /dev/kfd
        - name: dri
          mountPath: /dev/dri
      env:
        - name: HSA_OVERRIDE_GFX_VERSION
          value: "11.0.0"
      ports:
        - containerPort: 11434
          hostPort: 11434

  volumes:
    - name: ollama-data
      emptyDir: {}
    - name: kfd
      hostPath:
        path: /dev/kfd
        type: CharDevice
    - name: dri
      hostPath:
        path: /dev/dri
        type: Directory

---

# I want them in separate pods since I don't want open-webui to touch ollama's volumes
apiVersion: v1
kind: Pod

metadata:
  name: open-webui-pod

spec:
  containers:
    - name: open-webui
      image: ghcr.io/open-webui/open-webui:latest
      volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
      ports:
        - containerPort: 8080
          hostPort: 23456

  volumes:
    - name: open-webui-data
      emptyDir: {}

---

apiVersion: v1
kind: Service

metadata:
  name: ollama-service

spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
