---
- name: Create tmp dir
  tempfile:
    state: directory
    suffix: _fish_files
  register: fish_temp_dir

- name: Generate fish variables from bash variables
  command:
    cmd: vercajk fish --path {{ fish_temp_dir.path }} variables
  # generating vars file every time
  changed_when: true

- name: Rsync variables to fish config
  ansible.posix.synchronize:
    src: "{{ fish_temp_dir.path }}/variables"
    dest: "{{ home_dir }}/.config/fish/conf.d/"
    checksum: true
    recursive: true
    delete: true
    times: false

- name: Generate fish scripts from bash scripts in bashrc
  command:
    cmd: vercajk fish --path {{ fish_temp_dir.path }} scripts
  # generating scripts file every time
  changed_when: true

- name: Rsync scripts to fish config"
  ansible.posix.synchronize:
    src: "{{ fish_temp_dir.path }}/call_in_bash_scripts.fish"
    dest: "{{ home_dir }}/.config/fish/functions/"
    checksum: true
    recursive: true
    delete: true
    times: false
