- name: Get vercajk_path
  command:
    cmd: vercajk path
  register: vercajk_path

- name: Stow home folder with dotfiles
  command:
    cmd: stow -R . --dir={{ vercajk_path.stdout }}/dotfiles --target={{ home_dir }}

- name: Import bash
  import_tasks: bash.yml

- name: Import fish
  import_tasks: fish.yml
