---
- name: Install basic prog lang support
  package:
    name: "{{ prog_langs }}"
    state: present

- name: Install prog langs extra
  package:
    name: "{{ prog_langs_extra }}"
    state: present
  tags:
    - prog_langs_extra
