---
- name: Install basic prog lang support
  package:
    name: "{{ base_prog_langs }}"
    state: present

- name: Install weird prog langs
  package:
    name: "{{ weird_prog_langs }}"
    state: present
  tags:
    - weird_prog_lags
