exec-once = awww-daemon
exec-once = $WM_SCRIPTS/wallpapers.sh $HOME/.local/share/backgrounds/images/wallpapers 300
exec-once = waybar
exec-once = copyq --start-server
exec-once = nm-applet --indicator --no-agent
exec-once = swaync
exec-once = blueman-applet
exec-once = hypridle
exec-once = hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = darkman run
exec-once = $WM_SCRIPTS/workspaces.lua --refresh
exec-once = hyprpm reload -n

exec-shutdown = killall -q waybar swaync blueman-applet nm-applet copyq hypridle hyprpolkitagent awww-daemon darkman
