# layers
layerrule = blur on, match:namespace logout_dialog

# float utility windows
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:title ^(File Operation)(.*)$

# inhibit idle for fullscreen apps (video, games)
windowrule = idle_inhibit always, match:fullscreen 1

# copyq popup
windowrule = float on, match:class ^(com.github.hluk.copyq)$
windowrule = size 600 400, match:class ^(com.github.hluk.copyq)$

# rofi fzf floating terminals
windowrule = float on, match:title ^rofi-calc$
windowrule = size 600 300, match:title ^rofi-calc$
windowrule = center on, match:title ^rofi-calc$

windowrule = float on, match:title ^rofi-translate$
windowrule = size 700 400, match:title ^rofi-translate$
windowrule = center on, match:title ^rofi-translate$

windowrule = float on, match:title ^rofi-files$
windowrule = size 800 500, match:title ^rofi-files$
windowrule = center on, match:title ^rofi-files$

windowrule = float on, match:title ^rofi-websearch$
windowrule = size 600 200, match:title ^rofi-websearch$
windowrule = center on, match:title ^rofi-websearch$

windowrule = float on, match:title ^rofi-network$
windowrule = size 700 450, match:title ^rofi-network$
windowrule = center on, match:title ^rofi-network$
