---
- name: Setup fonts
  package:
    name: "@fonts"
    state: present

- name: Install awesome fonts
  package:
    name: "fontawesome-fonts"
    state: present

- name: Allow Copr repo for nerd fonts
  community.general.copr:
    name: "che/nerd-fonts"
    state: enabled

- name: Install nerd fonts
  package:
    name: "nerd-fonts"
    state: present
