---
- name: Enable copr repo for hyprland packages
  community.general.copr:
    name: solopasha/hyprland
    state: enabled

- name: Install hyprland
  package:
    name: hyprland
    state: present

# except flatpak apps, they are installed in user space
- name: Install packages needed for nice DE
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ hyprland_packages }}"

- name: Allow swaync Copr repo
  community.general.copr:
    name: erikreider/SwayNotificationCenter
    state: enabled

- name: Install swaync
  package:
    name: SwayNotificationCenter
    state: present
