---
- name: Install hyprland
  package:
    name: hyprland
    state: present

- name: Enable copr repo for hyprland packages
  community.general.copr:
    name: solopasha/hyprland
    state: enabled

# except flatpak apps, they are installed in user space
- name: Install packages needed for nice DE
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ hyprland_packages }}"
