---
- name: Set up fonts
  import_tasks: fonts.yml

- name: Set up hyprland window manager
  import_tasks: hyprland.yml

- name: Install KDE Plasma
  import_tasks: kde.yml
  tags:
    - kde

- name: Import sound and multimedia
  import_tasks: sound_and_multimedia.yml

- name: Install core gui packages
  package:
    name: "{{ gui_core_packages }}"
    state: present

- name: Install core gui packages for rpm based systems
  package:
    name: "{{ gui_core_packages_rpm }}"
    state: present
  tags:
    - rpm

- name: Install Papirus icon theme
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - papirus-icon-theme
    - papirus-icon-theme-dark
    - papirus-icon-theme-light
