---
- name: Install pip
  package:
    name: python3-pip
    state: present

- name: Install pip
  package:
    name: python3-devel, krb5-devel
    state: present

- name: Install python dev tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_dev_tools }}"
  tags:
    - dev_tools
